version: "3.8"

services:
    celery:
        build: .
        command: celery worker --app=WeatherTelegramBot.celery
        volumes:
            - .:/usr/src/app
        environment:
            - CELERY_BROKER=redis://:pc29bf52c9c48380d44b0e34d927a765b513dea2555b8a9d032f8660fd4a41dba@ec2-34-254-104-245.eu-west-1.compute.amazonaws.com:32559
            - CELERY_BACKEND=redis://:pc29bf52c9c48380d44b0e34d927a765b513dea2555b8a9d032f8660fd4a41dba@ec2-34-254-104-245.eu-west-1.compute.amazonaws.com:32559
        depends_on:
            - redis
    redis:
        image: "redis:alpine"

volumes:
    pgdata:


