version: "3.8"

services:
    celery:
        build: .
        command: celery worker --app=WeatherTelegramBot.celery
        volumes:
            - .:/usr/src/app
        environment:
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - redis
    redis:
        image: "redis:alpine"

volumes:
    pgdata:
